### ISSUE TITLE
Is it possible to ignore flashing cursor in the input fields? 

### ISSUE THREAD

**Issue by pavelkotau** [pazone/ashot#108]
after opening of proper page (let it be Login Page) cursor always flashing inside the login input field, and it is like 50/50 for passing a test or not. Is there any solution to ignore this flashing cursors inside input fields?

**Comment by marvelfrozen** [comment]
How about you click somewhere on the page before taking the screenshot?

**Comment by pavelkotau** [comment]
@gavrilfb It seems that it only the way to do that. But because ignoring specific color it is not the best idea, I think.

**Comment by pazone** [comment]
@pavelkotau Sure. Ignoring special colors may produce false-negative test results. Could you please describe how do you use selenium? I should say that you can avoid this and a lot of similar problems using proper selenium server configuration. Try [Seleniod](https://github.com/aerokube/selenoid) or similar solutions. It has simple configuration and provides reliable autoscaling facility for selenium.
