### ISSUE TITLE
Can't compare screenshots ignoring an element.

### ISSUE THREAD

**Issue by pavelkotau** [pazone/ashot#109]
Hello, everyone. I'm stacked and can't proceed with ignoring web element.

I have the next code:

`

    public class Ashot extends PageObject {
    @FindBy(xpath = "html/body/div[2]/div[2]/section")
    private WebElementFacade ignoredElement;

    ShootingStrategy mac = viewportRetina(100, 0, 0, 2);

    @Test
    public void ignoredElementTest() throws Exception {
        takesEntireScreenshotAndCompareIgnoring("expected.png", ignoredElement);

    }

    public void takesEntireScreenshotAndCompareIgnoring(String screenshotTitle, WebElementFacade... ignoredElements) {
        BufferedImage actualScreenshot = takeScreenshotIgnoringElement(ignoredElements);
        BufferedImage expectedScreenshot = loadImage(screenshotTitle);
        assertThat(areImagesEqual(expectedScreenshot, actualScreenshot), is(true));

    }

     private BufferedImage takeScreenshotIgnoringElement(WebElementFacade... ignoredElement) {
        Set<Coords> coords = getCoords(ignoredElement);
        Screenshot screenshot = new AShot()
                .ignoredAreas(coords)
                .shootingStrategy(mac)
                .takeScreenshot(getDriver());
        return screenshot.getImage();
    }

    private static Set<Coords> getCoords(WebElementFacade... ignoredElements) {
        Set<Coords> ignoredCoords = new HashSet<>();
        for (WebElementFacade element : ignoredElements) {
            Point point = element.getLocation();
            Dimension dimension = element.getSize();
            ignoredCoords.add(new Coords(point.getX(), point.getY(), dimension.getWidth(), dimension.getHeight()));
        }
        return ignoredCoords;
    }

    private static BufferedImage loadImage(String screenshotTitle) {
        try {
            return ImageIO.read(new File("src/test/resources/images/" + screenshotTitle + ".png"));
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static void writeImage(BufferedImage actualScreenshot, String screenshotTitle) {
        try {
            ImageIO.write(actualScreenshot, "png", new File("src/test/resources/images/" + screenshotTitle + ".png"));
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static boolean areImagesEqual(BufferedImage expected, BufferedImage actual) {
        return expected.getHeight() == actual.getHeight() &&
                expected.getWidth() == actual.getWidth() &&
                actual.getColorModel().equals(expected.getColorModel()) &&
                areImagesBuffersEqual(expected.getRaster().getDataBuffer(), actual.getRaster().getDataBuffer());
    }

    private static boolean areImagesBuffersEqual(DataBuffer expected, DataBuffer actual) {
        return actual.getDataType() == expected.getDataType() &&
                actual.getNumBanks() == expected.getNumBanks() &&
                actual.getSize() == expected.getSize() &&
                areImagesBytesEqual(actual, expected);
    }

    private static boolean areImagesBytesEqual(DataBuffer expected, DataBuffer actual) {
        for (int bank = 0; bank < expected.getNumBanks(); bank++) {
            for (int i = 0; i < expected.getSize(); i++) {
                if (expected.getElem(bank, i) != actual.getElem(bank, i)) {
                    return false;
                }
            }
        }
        return true;
    }

`

Where I'm trying to get screenshot and compare the entire screenshot with predefined one, ignoring webElement. But my tests still failed. it seems that nothing is ignored.  What I'm doing wrong?

**Comment by pazone** [comment]
Hi, @pavelkotau. AShot is already have a solution to compare screenshots. Your method `areImagesBytesEqual` just compares two DataBuffers and it doesn't know anything about ignored elements. This information is stored in `Screenshot` object. Please, consider the [comparison](https://github.com/yandex-qatools/ashot#screenshot-comparison) part of readme. Just use  `ImageDiffer` which consumes two `Screenshot` objects fulfilled with required data.
