### ISSUE TITLE
the scrolling web page screenshots taken in IE11 with selenium 3.5 and ashot is not working. it is creating partial image.

### ISSUE THREAD

**Issue by vinaygutta1** [pazone/ashot#110]
the scrolling web page screenshots taken in IE11 with selenium 3.5 and ashot is not working. it is creating partial image.

IE Version: 11
Selenium Version: Version 3.5.3
OS: 2012 R2 server
Java: 1.8

The below is the code used.

final Screenshot screenshot = new AShot()
                    .shootingStrategy(ShootingStrategies.viewportPasting(1000))
                    .takeScreenshot(driver);

            final BufferedImage image = screenshot.getImage();

            try {
                
                ImageIO.write(image, "png", new File("scrsht\\" + filename + "- ie -" + dateFormat.format(new Date()) + ".png"));

            } catch (IOException ex) {
                
                

            }

**Comment by pazone** [comment]
Hi, @vinaygutta1. Could you please attach a screenshot example?

**Comment by dqlambor** [comment]
![20171016_16_42_36](https://user-images.githubusercontent.com/27811176/31606621-d76fe832-b293-11e7-8ef9-e05036ab7651.png)
Hi @pazone , I got the same issue here.
AShot just take the last view of the entire page.
Here's my code:
try {
							Screenshot fpScreenshot = new AShot().shootingStrategy(ShootingStrategies.viewportPasting(1000))
									.takeScreenshot(driver);
							Thread.sleep(3000);
							BufferedImage fullScreen = fpScreenshot.getImage();
							// BufferedImage fullScreen = fpScreenshot.
							ImageIO.write(fullScreen, "PNG", new File(fileName + ".png"));
							System.out.println("---Screenshot Captured!!!!");
						} catch (IOException e) {
							e.printStackTrace();
						}
Please help...

**Comment by pazone** [comment]
As far as I remember you don't need to use `ShootingStrategies.viewportPasting(1000)` strategy. `new AShot().takeScreenshot(driver);` would have been enough.

**Comment by dqlambor** [comment]
I tried strategy. new AShot().takeScreenshot(driver) and it can only get the screenshot of top screen of the page ( without  scrolling down)
> As far as I remember you don't need to use ShootingStrategies.viewportPasting(1000) strategy. new AShot().takeScreenshot(driver); would have been enough.

**Comment by rovner** [comment]
@dqlambor, By default ie driver resizes browser window during screenshooting to document dimensions, so the whole document should be screenshooted with `new AShot().takeScreenshot(driver)`. But this could be not the case for some adaptive layouts and can be disabled with capability ie.enableFullPageScreenshot=false. Then you could try to capture screenshot with ` new AShot().shootingStrategy(ShootingStrategies.viewportPasting(1000))
.takeScreenshot(driver);`. Probably, this won't work either, becasuse ViewPortPastingStrategy was designed for ipad/android emulators and may not fit in ie. In this case the best choise is develop you onn strateegy for scrlling.

**Comment by pazone** [comment]
@dqlambor Could you please share the link to this page? I suppose that it can be uncommon.

**Comment by dqlambor** [comment]
Hi @pazone ,
Sorry that I can't share the link.
But I've tried with the current page https://github.com/yandex-qatools/ashot/issues/110 and still get the same issue.
![home_test](https://user-images.githubusercontent.com/27811176/31758112-4ad740a6-b4d6-11e7-81c5-addd773ce464.png)

**Comment by dqlambor** [comment]
@rovner , Thank you
I've writen some codes for taking whole page screenshot, it works but not good as expect :)

**Comment by pazone** [comment]
@dqlambor Could you please share your solution? Have you created a new shooting strategy?

**Comment by dqlambor** [comment]
@pazone : my solution is get the height of the page using Webelement eleHtml.getSize().getHeight();
then get driver screenshot > PageDown
then get driver screenshot > PageDown
then get driver screenshot > PageDown
...
until the end of page.
Each screenshot was drawed into an ImageBuffered using graphic.drawImage();
After that I got the result as expected :)

**Comment by ogasawara-shift** [comment]
With my short guessing, the following patch to `ViewportPastingDecorator.java` may solve this issue:

```diff
     protected int getCurrentScrollY(JavascriptExecutor js) {
-        return ((Number) js.executeScript("var scrY = window.scrollY;"
-                       + "if(scrY){return scrY;} else {return 0;}")).intValue();
+        if (js instanceof InternetExplorerDriver) {
+                return ((Number) js.executeScript("var scrY = window.pageYOffset;"
+                    + "if(scrY){return scrY;} else {return 0;}")).intValue();
+
+        } else {
+            return ((Number) js.executeScript("var scrY = window.scrollY;"
+                    + "if(scrY){return scrY;} else {return 0;}")).intValue();
+        }
     }
```

I'm not sure I should re-open this issue or create new issue, though.

**Comment by ogasawara-shift** [comment]
And I've modified `pom.xml` to use `InternetExplorerDriver` (update dependency from `selenium-remote-driver` to `selenium-java`), but I didn't anything to check backward-compatibility.

**Comment by naruoga** [comment]
Hello, with my short guessing, the following patch to `ViewportPastingDecorator.java` might solve this issue:

```diff
     protected int getCurrentScrollY(JavascriptExecutor js) {
-        return ((Number) js.executeScript("var scrY = window.scrollY;"
-                       + "if(scrY){return scrY;} else {return 0;}")).intValue();
+        if (js instanceof InternetExplorerDriver) {
+                return ((Number) js.executeScript("var scrY = window.pageYOffset;"
+                    + "if(scrY){return scrY;} else {return 0;}")).intValue();
+
+        } else {
+            return ((Number) js.executeScript("var scrY = window.scrollY;"
+                    + "if(scrY){return scrY;} else {return 0;}")).intValue();
+        }
     }
```

The patch below is also needed to modify `pom.xml` to use `InternetExplorerDriver`, change dependency from `selenium-remote-driver` to `selenium-java`, but I haven't done any backward-compatibility test yet...

**Comment by AbanoubErian** [comment]
Hi,
Actually i was facing the same issue with ashot while taking a screenshot for a full page on IE11 and after investigations i found that it seems that the root cause of this problem is related to the latest version of ashot 1.5.4, and its command which is
"new AShot().shootingStrategy(ShootingStrategies.viewportPasting(1000)).takeScreenshot(driver);"
so as a work around i used the old ashost version 1.4.4 which was working perfectly with ie11 using the below command:
"new AShot().shootingStrategy(new viewportpastingstrategy(1000)).takeScreenshot(driver);"
also the latest version is facing some issues with safari (duplicate the top section instead of taking the fullscreen screenshot) so we are waiting from ashot team a new update with those fixes

**Comment by AppiumIOSRuser** [comment]
Hi @naruoga ,
For me the below Changes worked without changing the Pom.xml 
I have updated These Methods: **getScreenshot** and **getCurrentScrollY** like below

 @Override
    public BufferedImage getScreenshot(WebDriver wd, Set<Coords> coordsSet) {
    	String browserName ="empty";
    	JavascriptExecutor js = (JavascriptExecutor) wd;
    	try {
    		
            Capabilities cap = ((RemoteWebDriver) wd).getCapabilities();
    		 browserName = cap.getBrowserName().toLowerCase();
		} catch (Exception e) {
			
		}
        
        int pageHeight = getFullHeight(wd);
        int pageWidth = getFullWidth(wd);
        int viewportHeight = getWindowHeight(wd);
        shootingArea = getShootingCoords(coordsSet, pageWidth, pageHeight, viewportHeight);

        BufferedImage finalImage = new BufferedImage(pageWidth, shootingArea.height, BufferedImage.TYPE_3BYTE_BGR);
        Graphics2D graphics = finalImage.createGraphics();

        int scrollTimes = (int) Math.ceil(shootingArea.getHeight() / viewportHeight);
        for (int n = 0; n < scrollTimes; n++) {
            scrollVertically(js, shootingArea.y + viewportHeight * n);
            waitForScrolling();
            BufferedImage part = getShootingStrategy().getScreenshot(wd);
            graphics.drawImage(part, 0, getCurrentScrollY(js,browserName)- shootingArea.y, null);
        }

        graphics.dispose();
        return finalImage;
    }


@Override  
protected int getCurrentScrollY(JavascriptExecutor js,String browsername) {
          int k=0;
          if (browsername.contains("internet explorer")) {
        	  k= ((Number) js.executeScript("var scrY = window.pageYOffset;"
                 + "if(scrY>0){return scrY;} else {return 0;}")).intValue();

      } else {
    	  k= ((Number) js.executeScript("var scrY = window.scrollY;"
                 + "if(scrY){return scrY;} else {return 0;}")).intValue();
      }
          
          return k;
    }

**Comment by naruoga** [comment]
Hm, it seems nice than my patch to check IE within JS code.  I'll try to update mine later (if I have free time :)
