### ISSUE TITLE
When two images has diff , how to find what is the difference in the images

### ISSUE THREAD

**Issue by harithapavuluri** [pazone/ashot#120]
Hi , 

 I am working on Ashot from past 5 days. I found  it very useful for comparing  two screenshot images. When I had see what is the difference in the image , there is no clear way to find difference in image. I copied my code below and attached screenshots what i am referring to. 

package sikulixapi;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;

import javax.imageio.ImageIO;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import ru.yandex.qatools.ashot.AShot;
import ru.yandex.qatools.ashot.Screenshot;
import ru.yandex.qatools.ashot.comparison.ImageDiff;
import ru.yandex.qatools.ashot.comparison.ImageDiffer;
import ru.yandex.qatools.ashot.shooting.ShootingStrategies;
import ru.yandex.qatools.ashot.util.ImageTool;

public class FullScreenshot {

	public static void main(String[] args) throws IOException, InterruptedException {
		// TODO Auto-generated method stub

		
		System.setProperty("webdriver.chrome.driver", "D:\\SeleniumDriver\\chromedriver.exe");
    	WebDriver driver=new ChromeDriver();

        driver.manage().timeouts().implicitlyWait(150,TimeUnit.SECONDS);

       driver.get("file:///C:/Users/Haritha/Desktop/example.html");
        
       
        
        BufferedImage expectedImage = ImageIO.read(new File(System.getProperty("user.dir")+"/imgs/aShot/colorChange.png"));

        System.out.println("\n expectedImage= "+expectedImage );
        Thread.sleep(5000);
        
        Screenshot screenshot = new AShot().shootingStrategy(
        		ShootingStrategies.viewportPasting(1000)).takeScreenshot(driver);
        BufferedImage image = screenshot.getImage();
        ImageIO.write(image, "PNG", new File(System.getProperty("user.dir")+"/imgs/aShot/localDemo.png"));
        

        BufferedImage actualImage = screenshot.getImage();
        
 
        
        ImageDiffer imgDiff = new ImageDiffer();

        ImageDiff diff = imgDiff.makeDiff(expectedImage,actualImage);
        
       
        
        BufferedImage diffImage = diff.getDiffImage();
        ImageIO.write(image, "PNG", new File(System.getProperty("user.dir")+"/imgs/aShot/diffImage.png"));
        
        System.out.println("\n diffImage= "+diffImage.getColorModel() );

        
        if(diff.hasDiff()){
        	System.out.println("Images are not same");
        }else { 
        	System.out.println("Images are same");
        }
        
        diff = imgDiff.makeDiff(diffImage,actualImage);
        //diff.getDiffImage()
        if(diff.hasDiff()){
        	System.out.println(" diff Image & actual image are not same"+ diff.getDiffImage().getData());
        }else { 
        	System.out.println("Images are same");
        }
        
        diff = imgDiff.makeDiff(diffImage,expectedImage);
        
        if(diff.hasDiff()){
        	System.out.println(" diff Image & xpected image are not same");
        }else { 
        	System.out.println(" expected & Diff Images are same");
        }
        
 
        
        driver.quit();

	}

}

![colorchange](https://user-images.githubusercontent.com/17870693/37146540-07a37ea8-22ea-11e8-97bf-11178670b072.png)
![localdemo](https://user-images.githubusercontent.com/17870693/37146546-0cce6d84-22ea-11e8-976c-63caa77f6774.png

In the above code, colorChange.png 's text color is blue and localDemo.png text color is black.   How can i get this info from diffImage class. 

How can i know that the text color is the difference in expected and actual image. 

Similarly, I wanted to know how can i get if some text missing from expected to actual or alignment  issues. 

Thanking you in advance,

aWaiting for your reply.

**Comment by harithapavuluri** [comment]
![localdemo](https://user-images.githubusercontent.com/17870693/37146776-c69484c4-22ea-11e8-8d3d-6ba42b0f31cc.png)

**Comment by harithapavuluri** [comment]
Can any one please comment on this issue

**Comment by harithapavuluri** [comment]
I got it working ,  a small mistake in my code. Hence closing this bug.

**Comment by the-mgk** [comment]
Hi, 
what was the bug? I'm interested in doing something similar.

**Comment by rajavkp** [comment]
Actual Image
![Actual](https://user-images.githubusercontent.com/38759141/69142182-47b7aa00-0aec-11ea-89d1-b153d1a1cb99.png)
Expected Image
![Expected](https://user-images.githubusercontent.com/38759141/69142184-48504080-0aec-11ea-9e6e-a1ba28e41c0d.png)
Difference Between 2 Images
![Difference](https://user-images.githubusercontent.com/38759141/69142183-47b7aa00-0aec-11ea-8627-f1a21dcccf44.png)

//---------------------------------------------------------------------------------------

package pkg1;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import ru.yandex.qatools.ashot.AShot;
import ru.yandex.qatools.ashot.Screenshot;
import ru.yandex.qatools.ashot.comparison.ImageDiff;
import ru.yandex.qatools.ashot.comparison.ImageDiffer;
public class ImageComparisonPositive 
{
	   public static void main(String args[]) throws Exception
	   {
		   try
		   {
	    	System.setProperty("webdriver.chrome.driver", "E:\\Rajagopal\\RajWorkspace\\Bancpay4X\\drivers\\ChromeDriver\\chromedriver.exe");
	 	   	WebDriver driver=new ChromeDriver();
	        driver.get("http://demo.automationtesting.in/Register.html");
	         
	        BufferedImage expectedImage = ImageIO.read(new File(System.getProperty("user.dir") +"\\ScreenShot\\Expected.png"));
	        
	        WebElement logoImage = driver.findElement(By.cssSelector("#imagetrgt"));
	        Screenshot logoImageScreenshot = new AShot().takeScreenshot(driver, logoImage);
	        BufferedImage actualImage = logoImageScreenshot.getImage();
	        ImageIO.write(logoImageScreenshot.getImage(),"PNG",new File(System.getProperty("user.dir") +"\\ScreenShot\\Actual.png"));
	                 
	        ImageDiffer imgDiff = new ImageDiffer();
	        ImageDiff diff = imgDiff.makeDiff(actualImage, expectedImage);        
	      //  Assert.assertFalse(diff.hasDiff(),"Images are Same");
	        BufferedImage diffImage = diff.getDiffImage();
	        
	        ImageIO.write(diff.getMarkedImage(),"PNG", new File(System.getProperty("user.dir")+"\\ScreenShot\\Difference.png"));
	        
	        System.out.println("\n diffImage= "+diffImage.getColorModel() );
		   }catch(Exception e) {System.out.println(e.getMessage());}         
    }
}

**Comment by Anoopkumars** [comment]
Please help, am getting similar issue where i want to know diffrence in image. Not sure how to do it.

**Comment by rajavkp** [comment]
Ya sure. You can refer my above code. Still if you have any double. Please mention here.
