### ISSUE TITLE
Unable to capture the url of the page in the screenshot using ashot

### ISSUE THREAD

**Issue by kishoreccaus** [pazone/ashot#128]
Hello Guys, 

Is it possible to capture the url of the page in the screenshot, bcoz the issues is sometimes the links are pointed to incorrect environments and we are able to identify that only in the url. Pls find below my code which I am using the capture the screenshots, but I am unable to capture the url part of the screenshot. 

Screenshot fpScreenshot = new AShot().shootingStrategy(ShootingStrategies.viewportPasting(1000)).takeScreenshot(DriverManager.getDriver());

ImageIO.write(fpScreenshot.getImage(),"PNG",new File(System.getProperty("user.dir") + "/target/ExtentReports/" + screenshotName));

I tried with and without the shootingstrategy but no luck.

Any help appreciated. 

Thanks
![mon_jul_30_16_11_21_aest_2018_1](https://user-images.githubusercontent.com/25767948/43380357-35d6895a-9414-11e8-973e-957af84868bb.PNG)

**Comment by ubermensch01** [comment]
@kishoreccaus AShot only takes a screenshot of the viewport of the browser, it doesn't make a screenshot of the browser itself. To capture the url of the browser at the time of making a screenshot use WebDriver's `getCurrentUrl()` method (`driver.getCurrentUrl()`).
