### ISSUE TITLE
Unable to capture screenshots under new folder by creating it in runtime using AShot utility

### ISSUE THREAD

**Issue by ketanna** [pazone/ashot#130]
I did create 'PassedTestSuiteScreens' folder in my project base directory, and I wanted when each day I run my scripts I want to create a new folder under this with folder name as "Today'sDate" ex: 04_09_2018 and paste all passed test screens under that.

I have below exception as it didn't find the specific path:-

java.io.FileNotFoundException: C:\Users\ketanna\Desktop\Test-Automation\CRMTestProject\PassedTestSuiteScreens\04_09_2018.\loginPageTitleTest_04_09_2018 19-19-57.png (The system cannot find the path specified)

Code using AShot utility: I am calling below method in Listener class

public static void takeFullPageScreenshot(String TestName) throws IOException{
		try {
		Thread.sleep(1000);
		String currentDir = System.getProperty("user.dir");
		String RunDate =  new SimpleDateFormat("dd_MM_yyyy").format(new Date());
		String filename =  new SimpleDateFormat("dd_MM_yyyy HH-mm-ss").format(new Date());
		Screenshot screenshot = new AShot().shootingStrategy(ShootingStrategies.viewportPasting(100)).takeScreenshot(driver);
		BufferedImage Image = screenshot.getImage();
		ImageIO.write(Image, "PNG", new File(currentDir+"/PassedTestSuiteScreens/"+RunDate+".//"+TestName+"_"+filename+".png"));
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

public void onTestSuccess(ITestResult result) {
			try {
				TestUtil.takeFullPageScreenshot(result.getName());
				//TestUtil.passedTestScreenShot(result.getName());
			} catch (IOException e) {
				e.printStackTrace();
			}
		}

Below code using java.io.File class has created a new folder and works fine-

public static void passedTestScreenShot(String TestName) throws IOException {
		try {
		Thread.sleep(1000);
		File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
		String currentDir = System.getProperty("user.dir");
		String RunDate =  new SimpleDateFormat("dd_MM_yyyy").format(new Date());
		String filename =  new SimpleDateFormat("dd_MM_yyyy HH-mm-ss").format(new Date());
		FileUtils.copyFile(scrFile, new File(currentDir+"/PassedTestSuiteScreens/"+RunDate+".//" +TestName+"_"+filename+".png"));
		System.out.println(TestName+ ":Test Success & Screenshot has been taken");
		}catch(Exception e){
			System.out.println("Exception while taking screenshot "+e.getMessage());
		}
		}

**Comment by kazurayam** [comment]
I suppose you need to create the parent directory yourself.

```
File outFile = new File(currentDir+"/PassedTestSuiteScreens/"+RunDate+".//"+TestName+"_"+filename+".png";
File parentDir = outFile.getParentFile();
parentDir.mkdirs()
ImageIO.write(Image, "PNG", outFile));
```

Commons IO's [FileUtils.copyFile](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FileUtils.html#copyFile(java.io.File,%20java.io.File)) creates directory automatically.

**Comment by ketanna** [comment]
Thanks! It works.
