### ISSUE TITLE
Trying to use Ignore Element but not sure how to set that for saved PNG reference image

### ISSUE THREAD

**Issue by apathan123** [pazone/ashot#138]
I am trying to use ignore element while saving scrennshot which is compared with already saved image. But while execution it is not ignoring that area. Is there a way to handle this?

**Comment by JAnton101** [comment]
Hi, yes.

Also, please share your code which is used for comparing.

I think you've missed this:
`expectedScreen.setIgnoredAreas(screen.getIgnoredAreas());`

Try this, it works for me:
```java
Screenshot screen = new AShot()
	.shootingStrategy(ShootingStrategies.viewportPasting(1000)) // depends on your goals
	.addIgnoredElement(By.cssSelector("#body")) // your ignored element
	.coordsProvider(coordsProvider)
	.takeScreenshot(driver, elem);
Screenshot expectedScreen = readImg(); // your function of whatever to take a master screen

expectedScreen.setIgnoredAreas(screen.getIgnoredAreas()); // set ignored coordinates before comparing for the master screen
expectedScreen.setCoordsToCompare(screen.getCoordsToCompare()); // set coordinates which are going to be compared for the master screen

ImageDiff diff = new ImageDiffer().makeDiff(expectedScreen, screen);
```

As you see the main idea that you should transfer all data about compared and ignored element from actual screen to expected before ImageDiffer().

And I see that this moment is missed in the guide for this library, looks like document issue.
[https://github.com/pazone/ashot#screenshot-comparison](url)

**Comment by apathan123** [comment]
> 
> 
> Hi, yes.
> 
> Also, please share your code which is used for comparing.
> 
> I think you've missed this:
> `expectedScreen.setIgnoredAreas(screen.getIgnoredAreas());`
> 
> Try this, it works for me:
> 
> ```java
> Screenshot screen = new AShot()
> 	.shootingStrategy(ShootingStrategies.viewportPasting(1000)) // depends on your goals
> 	.addIgnoredElement(By.cssSelector("#body")) // your ignored element
> 	.coordsProvider(coordsProvider)
> 	.takeScreenshot(driver, elem);
> Screenshot expectedScreen = readImg(); // your function of whatever to take a master screen
> 
> expectedScreen.setIgnoredAreas(screen.getIgnoredAreas()); // set ignored coordinates before comparing for the master screen
> expectedScreen.setCoordsToCompare(screen.getCoordsToCompare()); // set coordinates which are going to be compared for the master screen
> 
> ImageDiff diff = new ImageDiffer().makeDiff(expectedScreen, screen);
> ```
> 
> As you see the main idea that you should transfer all data about compared and ignored element from actual screen to expected before ImageDiffer().
> 
> And I see that this moment is missed in the guide for this library, looks like document issue.
> [https://github.com/pazone/ashot#screenshot-comparison](url)

Yes that was the issue. It worked now Thanks!!

**Comment by shrishail886** [comment]
Could you please provide whole code?

**Comment by apathan123** [comment]
> Could you please provide whole code?

You need code for ignoring element? That is already posted above

**Comment by shrishail886** [comment]
Thanks for the reply but issue is resolved now.
