### ISSUE TITLE
Screenshot returned is zoomed in and starts at wrong points

### ISSUE THREAD

**Issue by snehalharde** [pazone/ashot#151]
Actual Image: 
[
![ashot-qq](https://user-images.githubusercontent.com/34312893/62080904-895fd480-b21f-11e9-81af-b7b5b946ca27.png)
](url)

**Code for screenshot is:**
```
 Screenshot elementScreenShot = new AShot().shootingStrategy((ShootingStrategy) ShootingStrategies.scaling(200))
                .coordsProvider(new WebDriverCoordsProvider())
                .takeScreenshot(driver, element);
        BufferedImage image = elementScreenShot.getImage();
        //new image
        if (!actualImageFile.exists()) {
            ImageIO.write(image, "PNG", actualImageFile);
        } else {
            ImageIO.write(image, "PNG", differenceImageFile);
        }
        return elementScreenShot;
```

**CODE which is calling the screenshot is:**
```
 public static void webElementScreenshot(com.boomi.qa.base.BaseWebElement element) throws IOException {
        Screenshot screenshot = takeScreenshotWithElement(driver(), element);
        writeScreenshotToFolder(screenshot, differenceImageFile);
        doComparison(actualImageFile, differenceImageFile);
    }

```

```
public static void doComparison(File actualFile, File newFile) throws IOException {
        BufferedImage buffActualImage = ImageIO.read(actualFile);
        BufferedImage buffNewImage = ImageIO.read(newFile);

        ImageDiffer imgDiff = new ImageDiffer();
        ImageDiff compare = imgDiff.makeDiff(buffActualImage, buffNewImage);

        BufferedImage diffImage = compare.getMarkedImage();
        if (compare.hasDiff()) {
            ImageIO.write(diffImage, "PNG", differenceFileForParent);
        } 
```

 ` private static BaseWebElement loginPanelCss = new BaseWebElement("#login>div:nth-child(4)>div>div.loginPanelOuter>div>div.formPanel", "css");`

Expected Image:

![image](https://user-images.githubusercontent.com/34312893/62081643-0d668c00-b221-11e9-9cf9-357be86d6085.png)

 What am i missing, please advice?

**Comment by JAnton101** [comment]
`ShootingStrategies.scaling(200)` why do you use it?
Have you tried it with the default Shooting strategy and what Webdriver (I mean Chrome or FireFox) do you use?
Is it an animated element?
If yes, have you tried to add timeout?
Are you sure in your CSS locator?

**Comment by Shardeboomi** [comment]
It was a screen resolution issue. i used scaling to manage it.

**Comment by kazurayam** [comment]
Do you use Windows10?
I have ever experienced a problem that Windows10's View Display setting may affect taking screenshots. See the following:
- https://forum.katalon.com/t/taking-entire-page-screenshot-using-ashot-in-katalon-studio/12429/13

**Comment by valfirst** [comment]
@Shardeboomi is the issue still reproduced?

**Comment by Shardeboomi** [comment]
This was due to screen resolution.

**Comment by snehalharde** [comment]
It was screen resolution issue.

**Comment by AbhishekBaseshankar** [comment]
Call below method before taking screeshot to avoid the issue of getting crop images.
void ZoomOut() throws AWTException{
		Robot robot = new Robot();
		for (int i = 0; i < 5; i++) {

				robot.keyPress(KeyEvent.VK_CONTROL);
				robot.keyPress(KeyEvent.VK_SUBTRACT);
				robot.keyRelease(KeyEvent.VK_SUBTRACT);
				robot.keyRelease(KeyEvent.VK_CONTROL);
				
			}
	}
