### ISSUE TITLE
I used ashot in mobiles but it is giving different screenshots in Android and IOS.

### ISSUE THREAD

**Issue by sridhar73-hub** [pazone/ashot#158]
Screenshot Screenshot = new AShot().shootingStrategy(ShootingStrategies.viewportRetina(1000, 0, 0, 4.0f)).takeScreenshot(webdriver);

Above code working in android but In IOS not working.
![4](https://user-images.githubusercontent.com/55492661/65155334-be7fea80-da4a-11e9-8af7-6339c53c1d08.png)

In android i am getting screenshot like above.

![4](https://user-images.githubusercontent.com/55492661/65155491-03a41c80-da4b-11e9-8dd9-304bd73f6f55.png)

**Comment by sridhar73-hub** [comment]
Second screenshot in IOS.

**Comment by valfirst** [comment]
@sridhar73-hub try to change dpr to 2.0 for iOS:
```java
Screenshot Screenshot = new AShot().shootingStrategy(ShootingStrategies.viewportRetina(1000, 0, 0, 2.0f)).takeScreenshot(webdriver);
```

**Comment by sridhar73-hub** [comment]
Thannk you @valfirst it is working in IOS but in android not taking complete screen, i mean Half of the page from let to right like below

![4](https://user-images.githubusercontent.com/55492661/65168086-69030800-da61-11e9-820d-c58bae96ab57.png)

Working in IOS But it is taking header and footer also for every capture, like below.

![4](https://user-images.githubusercontent.com/55492661/65168435-242ba100-da62-11e9-8b68-7aed4fdeaf0a.png)

**Comment by valfirst** [comment]
@sridhar73-hub you should use different dpr values, different devices/emulators have different dpr-s

**Comment by sridhar73-hub** [comment]
okay, working fine Thank you @valfirst.
