### ISSUE TITLE
takeScreenshot(WebDriver driver, WebElement elements)

### ISSUE THREAD

**Issue by Shardeboomi** [pazone/ashot#161]
To define webelements , my framework has baswebElement class that extends webelement class.
when i pass the baswebelements, i get bad argument error.

**Comment by valfirst** [comment]
@Shardeboomi what is your issue? could you please provide details?

**Comment by Shardeboomi** [comment]
webelements are defined like below
private static BaseTextBox password = new
BaseTextBox("input[placeholder='Password']", "css");
when i pass  password    in takescreenshot method, i get error that this
method accept webelements.

**Comment by valfirst** [comment]
@Shardeboomi please provide error details

**Comment by Shardeboomi** [comment]
[image: image.png]

**Comment by valfirst** [comment]
@Shardeboomi it seems you tried to attach image, but it's not shown

**Comment by valfirst** [comment]
@Shardeboomi please provide error details

**Comment by osyanin** [comment]
I hope this helps

Example from Selenide: 

`open();`

`        WebElement expectedElement = $(cssSelector);`

`        Screenshot main = new AShot()`
`                .coordsProvider(new WebDriverCoordsProvider())`
`                .takeScreenshot(getWebDriver(), expectedElement);`

**Comment by valfirst** [comment]
@osyanin what is an error you are facing with?

**Comment by osyanin** [comment]
Sorry, didn' tagged. 
It was example for @Shardeboomi
