### ISSUE TITLE
Allow withIgnoredColor() method to have RGB colorCode Value Support

### ISSUE THREAD

**Issue by anandbhagwat** [pazone/ashot#170]
This Method :
        ImageDiffer imgdiffer = new ImageDiffer().withIgnoredColor(Color.RED);

Above method only support Color Name but not the exact Color Code

**Comment by valfirst** [comment]
@anandbhagwat use the corresponding `Color` constructor to create RGB-based instances: https://docs.oracle.com/javase/8/docs/api/java/awt/Color.html#Color-float-float-float-
