### ISSUE TITLE
Support for cutting out elements from screenshot

### ISSUE THREAD

**Issue by nicodn** [pazone/ashot#172]
Hello, thanks for the nice library!

I wanted to ask if ashot supports anything like cutting out elements from a screenshot regardless of the comparison situation. For example I'd like to take screenshots with elements removed or blocked out.
I wrote a quick snippet and I'm able to do this like so:
```
public class CutOutStrategy extends SimpleShootingStrategy {
        @Override
        public BufferedImage getScreenshot(WebDriver wd, Set<Coords> coords) {
            final BufferedImage screenshot = getScreenshot(wd);
            final Graphics g = screenshot.getGraphics();
            g.setColor(Color.BLACK);
            try {
                for (Coords coord : coords) {
                    g.fillRect(coord.x, coord.y, coord.width, coord.height);
                }
            } finally {
                g.dispose();
            }
            return screenshot;
        }
}
```
Then I call it:
```
final List<WebElement> cutOutElements = driver.findElements(By.xpath("//*[@class=\"excludeThisClass\"]"));
final Screenshot screenshot = new AShot().shootingStrategy(new CutOutStrategy()).takeScreenshot(driver, cutOutElements);
```

Is there support for this already and I'm missing it? If not, where would you recommend that I could add it? I would love to contribute!
Thanks!

**Comment by nicodn** [comment]
I think I've found a better way using an `ImageCropper`:

```
public static class CutOutStrategy extends ImageCropper {

        @Override
        protected Screenshot cropScreenshot(BufferedImage image, Set<Coords> coords) {
            final Graphics g = image.getGraphics();
            g.setColor(Color. BLACK);
            try {
                for (Coords coord : coords) {
                    g.fillRect(coord.x, coord.y, coord.width, coord.height);
                }
            } finally {
                g.dispose();
            }
            return new Screenshot(image);
        }
    }
```

Does this make more sense?

**Comment by valfirst** [comment]
@nicodn IMHO any of the provided solutions is ok, if it leads the required result, do you have any particular issues or problems?

**Comment by nicodn** [comment]
Nope, I just wanted to make sure the approach made sense and felt like sharing this idea - I think it could combine well with the feature that ignores based on pixels of predefined color too

It seems to be working now with the second approach, thanks @valfirst
