### ISSUE TITLE
Unable to click on a button using Content-desc in appium

### ISSUE THREAD

**Issue by knsaicharan** [pazone/ashot#173]
I'm new to testing in Appium. I was able to set everything up and to run the test. I used UiAutomatorViewer to get access to some Buttons, now I need to Click on a Button, but I just got the Cont-desc. **I tried the following XPaths but I ended up getting an error**. Any Help would be nice.

1. @FindBy(xpath = "//*[@contentDescription='SIGN IN     log in ']")
2. driver.FindElement(By.XPath("//android.widget.Button[@content-desc='SIGN IN     log in ']")).Click();
3. driver.FindElement(By.Name('SIGN IN     log in ')).Click();
4. **driver.FindElement(By.Xpath(//*[@Class='android.view.View'** OR @content-desc='SIGN IN     log in '])).Click();
![Annotation](https://user-images.githubusercontent.com/54312560/69934499-141b4d80-14f8-11ea-8470-0e8bef3c1f26.jpg)

**Comment by valfirst** [comment]
@knsaicharan how is it related to AShot project? Could you please provide any details?

**Comment by knsaicharan** [comment]
@valfirst oh.. I'm sorry it's by mistake I've mentioned in this project. It's actually an issue on the mobile automation project which I'm working currently on.
