### ISSUE TITLE
Black areas in screenshot at small(mobile) resolutions 

### ISSUE THREAD

**Issue by SheffBRC** [pazone/ashot#184]
`actualScreenshot = ashot.coordsProvider(new WebDriverCoordsProvider()).shootingStrategy(ShootingStrategies.viewportPasting(1000)).takeScreenshot(driver, driver.findElement(By.cssSelector(selector)));`

When I try capture single elements problem is appear also. As i mind It depends on viewport pasting value. But what value should be?

![image](https://user-images.githubusercontent.com/15000715/72428618-c3557080-3796-11ea-86cb-8c932b7332cd.png)

**Comment by valfirst** [comment]
@SheffBRC 
> As i mind It depends on viewport pasting value.

Are you talking about `ShootingStrategies.viewportPasting(1000)`? `1000` is a wait time between 2 scrolls in milliseconds. I don't think it may somehow introduce such black bars on screenshots.

Could you please provide full example to reproduce the issue? (code snippet, browser/device configuration, etc.)

**Comment by SheffBRC** [comment]
You're right, but changing of this value affects the black bars size
[MainPageTest_WoM.zip](https://github.com/pazone/ashot/files/4064908/MainPageTest_WoM.zip)

url - http://watchesofmayfair.com/

**Comment by valfirst** [comment]
@SheffBRC I recommend to provide an [SSCCE (Short, Self Contained, Correct (Compilable), Example)](http://sscce.org/) in future, the code from the attached neither short nor self contained.

However I've tried to open http://watchesofmayfair.com/, and I see that the size of the page is changed dynamically in mobile resolution. It's caused by the animation in the slider on the page top. It's not an AShot issue.

**Comment by SheffBRC** [comment]
@SheffBRC 
I'm removing animation banner on the top before each capture

`	private void removeBanner() {
		JavascriptExecutor js= (JavascriptExecutor) driver;
		js.executeScript("jQuery('.top-banner').remove()");
	}
`

You can't see it on image of first post

**Comment by valfirst** [comment]
@SheffBRC in this case please provide an [SSCCE (Short, Self Contained, Correct (Compilable), Example)](http://sscce.org/).

**Comment by valfirst** [comment]
@SheffBRC checking the provided code I can see:
```java 
...
private boolean scroll = false;
...
private void removeBanner() {
	JavascriptExecutor js= (JavascriptExecutor) driver;
	js.executeScript("jQuery('.top-banner').remove()");
}
...
private void scrolling() {
  if (scroll) {
    driver.findElement(By.tagName("body")).sendKeys(Keys.END);
    sleep(500);
    driver.findElement(By.tagName("body")).sendKeys(Keys.HOME);
    removeBanner();
    sleep(1000);
  }
}
```
`scroll` is always `false`, so `removeBanner` is not invoked

**Comment by SheffBRC** [comment]
**WebDriver:**

`		ChromeOptions ChromeOptions = new ChromeOptions();
		ChromeOptions.addArguments("window-size=375,667", "--no-sandbox");
		ChromeOptions.addArguments("--headless");
		driver = new ChromeDriver(ChromeOptions);
`

**Screen Capture:**

`Screenshot actualScreenshot = ashot.coordsProvider(new WebDriverCoordsProvider()).shootingStrategy(ShootingStrategies.viewportPasting(vportPast)).takeScreenshot(driver, driver.findElement(By.cssSelector("body")));`

**Comment by SheffBRC** [comment]
@valfirst 
Yes, I'm really forget set scroll to true... Thank you so much and excuse me for troubling
