### ISSUE TITLE
Take screenshot of floating popup

### ISSUE THREAD

**Issue by stubbsyy** [pazone/ashot#187]
Is there a way to take an image of a popup at the top, but ignore it when the screen scrolls and the popup follows the scroll?

**Comment by valfirst** [comment]
Do you have a sample page and an [SSCCE (Short, Self Contained, Correct (Compilable), Example)](http://sscce.org/) ?

**Comment by stubbsyy** [comment]
Thank you for the quick reply. I was actually able to get it figured out. I had a memory leak with using an excel workbook that was causing the shot utility to slow down. Once I figured out the memory leak with excel everything started working perfectly.
