### ISSUE TITLE
Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only

### ISSUE THREAD

**Issue by pythonmeister-zz** [pazone/ashot#194]
I get the following error:

org.openqa.selenium.remote.Augmenter     : Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only (instance class was: class org.openqa.selenium.chrome.ChromeDriver)

Selenium version 3.141.59.

**Comment by pythonmeister-zz** [comment]
Problem disappears by using ashot 1.5.4.

**Comment by valfirst** [comment]
@pythonmeister could you please provide an [SSCCE (Short, Self Contained, Correct (Compilable), Example)](http://sscce.org/) ?
