### ISSUE TITLE
Image Comparison failing

### ISSUE THREAD

**Issue by prateek-mehta** [pazone/ashot#195]
I am capturing image of elemnt and that same time taking same image and comparing both the images then i am getting that images are identical but when i am doing same process and saved one ss and again following same procedure and taking ss then it is saying image difference

**Comment by valfirst** [comment]
@prateek-mehta could you please provide an [SSCCE (Short, Self Contained, Correct (Compilable), Example)](http://sscce.org/) ?

**Comment by prateek-mehta** [comment]
I am attaching some images so that you can relate i tried to find what is actual difference also
![actualFieldEditedImage](https://user-images.githubusercontent.com/59059612/80620940-422f9a00-8a64-11ea-921f-bd979f4e20dc.png)
![differenceFieldEditedImage](https://user-images.githubusercontent.com/59059612/80620942-4360c700-8a64-11ea-95e3-951d7b49babf.png)
![expectedFieldImageEditedPage](https://user-images.githubusercontent.com/59059612/80620944-4360c700-8a64-11ea-94d3-f4b11d9c3649.png)

**Comment by prateek-mehta** [comment]
First and third image are exactly same but still giving difference

**Comment by valfirst** [comment]
@prateek-mehta images are not enough, please use SSCCE reference for the guidance

**Comment by prateek-mehta** [comment]
I have used the code for capturing ss first of particular ss let suppose ss1 and at same time when i compared with runtime image captruing same image it worked fine showed no difference but then i saved image1 ss in my folder and second time again went to same page and captured ss again but this time it showed me image has some difference

**Comment by prateek-mehta** [comment]
Is it possible to neglect small difference?

**Comment by pazone** [comment]
@prateek-mehta I assume your image is in jpeg or in other format with fuzzy rendering, right? You can specify the `diffSizeTrigger` to your `DiffMarkupPolicy`. 

```
DiffMarkupPolicy myMarkup = new PointsMarkupPolicy().setDiffSizeTrigger(42) // if a diff has 42 different pixels, it's gonna be not counted as a difference
ImageDiffer differ = new ImageDiffer().withDiffMarkupPolicy(myMarkup) ...
```

**Comment by pazone** [comment]
I would close it if you don't mind.
