### ISSUE TITLE
Getting error while taking screenshot in mobile for failed test case using ITestLister "java.lang.NullPointerException 	at Qaddoo.BaseMethod.getScreenshot(BaseMethod.java:63)" even i have initialize the driver

### ISSUE THREAD

**Issue by priyanka-tomer** [pazone/ashot#201]
My code:

TestNG version:7.3.0
Appium client:7.3.0
java:8
Selenium jar:3.141.59

package Qaddoo;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.URL;
import java.util.Properties;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.MobileCapabilityType;

public class BaseMethod {
	
	
	public static AndroidDriver<AndroidElement>  driver;
	
	
	
	
	public static AndroidDriver<AndroidElement> Capabilities(String appNAme) throws IOException
	{
		
				
		FileInputStream fis=new FileInputStream(System.getProperty("user.dir")+"\\src\\main\\java\\Qaddoo\\global.properties");
		
		 Properties prop= new Properties();
		 prop.load(fis);
				 
		// TODO Auto-generated method stub
				//appimum code
				File appDir= new File("Src");				
				File app=new File(appDir,  (String) prop.get(appNAme));		
							
				DesiredCapabilities cap= new DesiredCapabilities();
				String device=(String) prop.get("device");
				cap.setCapability(MobileCapabilityType.DEVICE_NAME, device);				
				//cap.setCapability(MobileCapabilityType.AUTOMATION_NAME,"uiautomator2");				
				cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());						
				cap.setCapability("autoGrantPermissions", "true");
				URL url=new URL("http://127.0.0.1:4723/wd/hub");
				AndroidDriver<AndroidElement> driver=new AndroidDriver<>(url,cap);
				return driver;			
				
	}
	
	//Take Screenshot Method
	
	

	

	public static void getScreenshot(String s) throws IOException
	{
	

	File scrfile1=((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
	
	FileUtils.copyFile(scrfile1,new File(System.getProperty("user.dir")+"\\"+s+".png"));
	
	
	}
	
	
				

				
		

	}
	

	

Listener code:
package resources;

import java.io.IOException;

import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;

import Qaddoo.BaseMethod;

public class Listeners implements ITestListener{

	

	@Override
	public void onTestStart(ITestResult result) {
		// TODO Auto-generated method stub
		System.out.println("Test Started");
	}

	@Override
	public void onTestSuccess(ITestResult result) {
		// TODO Auto-generated method stub
		
		System.out.println("Test Success");
		
		
		
	}

	@Override
	public void onTestFailure(ITestResult result) {
		// TODO Auto-generated method stub
		//screenshot 
		String s=result.getName();
		System.out.println("failure stared");
		try {
		BaseMethod.getScreenshot(s);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		
	}

	@Override
	public void onTestSkipped(ITestResult result) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onTestFailedButWithinSuccessPercentage(ITestResult result) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onStart(ITestContext context) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onFinish(ITestContext context) {
		// TODO Auto-generated method stub
		
	}
	
	

}

Error Log:
java.lang.NullPointerException
	at Qaddoo.BaseMethod.getScreenshot(BaseMethod.java:63)
	at resources.Listeners.onTestFailure(Listeners.java:43)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1655)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1639)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1183)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)

**Comment by valfirst** [comment]
`driver` variable is not initialized at line:
```java
File scrfile1=((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
```
that leads to `NullPointerException`

**Comment by priyanka-tomer** [comment]
@valfirst I initialize the driver in base class public static AndroidDriver<AndroidElement>  driver; but still return null pointer exception, Could you please assist how can i intiaze the driver here to overcome the null pointer exception error.

**Comment by valfirst** [comment]
the provided code doesn't have `driver` field initialization
