### ISSUE TITLE
@valfirst I initialize the driver in base class public static AndroidDriver<AndroidElement>  driver; but still return null pointer exception, Could you please assist how can i intiaze the driver here to overcome the null pointer exception error.

### ISSUE THREAD

**Issue by priyanka-tomer** [pazone/ashot#202]
@valfirst I initialize the driver in base class public static AndroidDriver<AndroidElement>  driver; but still return null pointer exception, Could you please assist how can i intiaze the driver here to overcome the null pointer exception error.

_Originally posted by @priyanka-tomer in https://github.com/pazone/ashot/issues/201#issuecomment-717712588_

**Comment by valfirst** [comment]
Not an issue. Closing
