### ISSUE TITLE
Changing color of diff marking 

### ISSUE THREAD

**Issue by apathan123** [pazone/ashot#209]
HI Is it possible to mark differrences in some other color tahn red. I ahve lot of red elements on screen and its difficult to spot the differrrnece at times.

**Comment by valfirst** [comment]
yes, it's possible:
https://github.com/pazone/ashot/blob/41a81919b40cc745d0652eae487e1f2ff54c5c41/src/main/java/pazone/ashot/comparison/DiffMarkupPolicy.java#L23-L26

**Comment by apathan123** [comment]
THanks for teh swift response.
Can you help me get this in code. Apologies but not very sure if I am doing
it correctly

ImageDiff diff = (new ImageDiffer()).makeDiff(actual,
expected).withDiffSizeTrigger(200);
BufferedImage diffImage = diff.getMarkedImage();

**Comment by valfirst** [comment]
Just set pre-configured `DiffMarkupPolicy`:
https://github.com/pazone/ashot/blob/41a81919b40cc745d0652eae487e1f2ff54c5c41/src/main/java/pazone/ashot/comparison/ImageDiffer.java#L47-L50

**Comment by apathan123** [comment]
Thanks so much. Got it working!
