### ISSUE TITLE
How to ignore fixed element when we using shootingStrategy to capturing the entire page.

### ISSUE THREAD

**Issue by ClaudeJiang** [pazone/ashot#274]
The fixed element always above other elements when we used shootingStrategy to capturing the entire page.
How can we ignore it?

**Comment by bloodgang94** [comment]
Hiding an element before capturing, C# example
`((IJavaScriptExecutor)((IWrapsDriver)element).WrappedDriver).ExecuteScript($"arguments[0].style.visibility='hidden'", element);`

**Comment by valfirst** [comment]
Fixed by #389
