### ISSUE TITLE
No full page screenshot when using PhantomJS driver

### ISSUE THREAD

**Issue by dreadangel** [pazone/ashot#92]
Hi all,
I'm using Ghost Driver + Selenium in order to create a headless browser testing. 
Using aShot for full page screenshot does not return the desired result - only the actual state (same result is I would use Selenium)

 pom:

    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-server</artifactId>
        <version>3.0.1</version>
    </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>3.0.1</version>
        </dependency>

        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>phantomjsdriver</artifactId>
            <version>1.3.0</version>
        </dependency>

        <dependency>
            <groupId>ru.yandex.qatools.ashot</groupId>
            <artifactId>ashot</artifactId>
            <version>1.5.2</version>
        </dependency>`

block code:

    DesiredCapabilities caps = new DesiredCapabilities();
    caps.setJavascriptEnabled(true); // enabled by default
    caps.setCapability(
    		PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY,
		    "phantomjs.exe"
    );
    
    WebDriver driver = new PhantomJSDriver(caps);
    driver.manage().window().maximize(); //!!!
    //driver.manage().window().setSize(new Dimension(1920, 2080));///??? not s solution
	
    driver.get("http://some.url");
    
    WebElement userName = driver.findElement(By.id("login-form-username"));
    WebElement passWord = driver.findElement(By.id("login-form-password"));
    
	userName.sendKeys("username");
    passWord.sendKeys("password");
    passWord.submit();
    Thread.sleep(2500);
    
    Screenshot screenshot =
			new AShot().takeScreenshot(driver);

    ImageIO.write(screenshot.getImage(), "PNG", new File("screenshot_1.png"));
    
    driver.quit();

resulting screenshot
![screenshot_1](https://cloud.githubusercontent.com/assets/1151809/21800621/1b8d5624-d727-11e6-91a5-89b3aac2e615.png)

Any suggestions?

**Comment by baev** [comment]
Summon @pazone

**Comment by fescobar** [comment]
@dreadangel what is the stack trace, it could be something like this?
`
java.lang.IllegalArgumentException: Width (0) and height (0) must be > 0
	at java.awt.image.SampleModel.<init>(SampleModel.java:126)
	at java.awt.image.ComponentSampleModel.<init>(ComponentSampleModel.java:146)
	at java.awt.image.PixelInterleavedSampleModel.<init>(PixelInterleavedSampleModel.java:87)
	at java.awt.image.Raster.createInterleavedRaster(Raster.java:641)
	at java.awt.image.Raster.createInterleavedRaster(Raster.java:278)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:376)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:46)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:35)
	at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:145)
`

**Comment by valfirst** [comment]
Closing because Phantom JS is dead: 
 - https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
 - https://github.com/ariya/phantomjs/issues/15344
